### ISSUE TITLE
System tests for VDSWrapperPart

### ISSUE THREAD

**Issue by GDYendell** [dls-controls/pymalcolm#210]
Most of the functionality of VDSWrapperPart relies on HDF5 files existing and being in the process of writing at run-time. Any unit tests will be fairly limited in scope; this really needs a system test.

A simple python script could write out a couple of HDF5 files with the relevant datasets. It would need to be written with SWMR compatibility and will therefore need a custom install of HDF5 1.10.1 (?) to build h5py against in the travis build.

**Comment by ulrikpedersen** [comment]
If you do need to custom install HDF5 1.10.1 on travis then make sure that you cache the install directory and condition the build to only run if the cache is not there... https://docs.travis-ci.com/user/caching

**Comment by MattTaylorDLS** [comment]
As far as I can tell. To get this unit test to work, I need to pip install h5py with the most up to date binaries of hdf5, (after setting the HDF5_DIR environment path to point to the hdf5 library). Can I get Travis to download the hdf5 src from somewhere, unzip it, compile it etc?, and then get the path of where the binaries are?

I then want to not do this again once it has been done once, If i do this on the pull request branch, when it's merged in to master, will the hdf5 version on master be updated too? Or will I have to merge it, run it once to update the version on master, and then checking in the 'undo' of this update hdf5 version?

**Comment by GDYendell** [comment]
As discussed, I think odin-data does this successfully.

**Comment by MattTaylorDLS** [comment]
Yep thanks Gary. Copied the odin-data scripts to do it and seems to work ok

**Comment by MattTaylorDLS** [comment]
Done on #228
