### ISSUE TITLE
CONTRIBUTING.rst out of date

### ISSUE THREAD

**Issue by BenBradnick** [dls-controls/pymalcolm#322]
Now that we have moved to using pipenv by default I presume this should also be updated to reflect this change.

- Update running the tests to use Pipfile and pipenv
- Code styling to mention black, flake8 and isort (also mention mypy?)
- Update how to build docs

One thing I noticed was that it mentioned using dashes for release numbers until Python 3. Should we now swap to using periods?

**Comment by thomascobb** [comment]
Yes, could you update to as many of the settings from dls_python3_template_module as possible please?
